[http.middlewares.simpleAuth.basicAuth]
  users = [
    "please:$apr1$sIoM6/3M$OeA4TXsmF9mIh1BBdBTIf1"
  ]

[http.routers.api]
  rule = "Host(`example.net`)" # Módosítani sajátra
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "letsEncrypt"

